/* Speaker notes for ttc-embedding-image-tagging-2026. window.NOTES[i] = {n, sec, title, note}
   Teleprompter script. Every line is a COMPLETE, natural sentence you read aloud.
   Annotations:  line break = breathe / pause   *word* = stress it   // = a longer beat
   No dashes. Keep 1:1 with index.html (26 slides). */
window.NOTES = [
  { n:1, sec:45, title:"Title",
    note:`Hello everyone.
My name is Han Xiao.
I run the model training and inference team at *Elastic*.//
In my last talk, I spoke about test-time compute for *search*.
And I said search is all about test-time compute,
because you kind of spend compute at test time to buy relevance,
by building a different pipeline for each query.//
Today I want to push that same idea one step further,
to unlock new capabilities, like image tagging.
In particular, I will show you how to use
a frozen jina-embeddings-v5-omni *embedding* model
to do image tagging, purely at test time.`},

  { n:2, sec:44, title:"The result, first",
    note:`Let me show you what I want to achieve.//
These are nine real photos from my Mac Studio.
You can see some landscapes from San Jose,
a price tag from Costco,
my teammate, my SSD drive,
and comics I got for my mom.
So nothing here is cherry picked.//
Seventy-five milliseconds per image, on this machine.//
And below each photo are the labels,
generated by the v5-omni model.
There is no training anywhere in the pipeline.
It is purely test-time compute.
And the real question is *which kind* of test-time compute pays for it.`},

  { n:3, sec:38, title:"Problem formulation",
    note:`Let me state the problem precisely.//
We are given one embedding model,
jina-embeddings-v5-omni-nano,
about a billion parameters,
with image and text living in one space.
And we are given one image.//
The output we want is words for *every* object in that image.
Multi-label, and open vocabulary.//
The model is frozen. All of its weights.
It is a retrieval encoder,
with no tagging head and no classifier.
It was never trained for this.//
What we allow ourselves is computation at inference time,
over the model's own outputs, and *nothing* else.
Training-free. No second model.
No dictionaries, and no part-of-speech taggers.//
So whatever tagging ability shows up
has to come from *test-time compute of the embedding model*.
That is the game.`},

  { n:4, sec:44, title:"How test-time scaling works",
    note:`Before the method, let me give you one piece of vocabulary,
because at first glance these options all look the same.//
A frozen encoder's inference budget takes roughly three forms.//
Family *A* is a deeper pass.
You read more of the one pass you already ran,
every patch vector, not just the pooled one.
If you have done retrieval, you know this.
Late interaction. ColBERT.
The information is reclaimed from *inside* the pass.//
Family *B* is more passes.
You run the frozen encoder *again*, on new views.
Split a document. Crop an image. Re-encode.
The information is acquired from the *input*.//
Family *C* is bootstrap.
You transform the vectors you already have,
with whitening, propagation, optimal transport.
Nothing new enters.//
It is the same frozen encoder in all three.
The only difference is what enters the computation.`},

  { n:5, sec:36, title:"Two research questions",
    note:`So I ask two questions, in increasing depth.//
Question one.
Can a frozen embedding model *become* an image tagger,
through test-time compute alone?
Prior work pays for tagging,
either with training, or with extra resources.
The RAM line trains over curated tags.
TagCLIP and PIAA are training-free,
but they assume the class list is *given*,
and they lean on WordNet and part-of-speech tools.
We allow none of that.//
And question two, if it can.
*Which* test-time compute actually scales the accuracy?
Re-processing the features, family C, where the literature bets?
Or new information, families A and B?`},

  { n:6, sec:48, title:"Architecture",
    note:`Now let me open the model up,
because the whole method lives in this one picture.//
This entire blue block is *one* released checkpoint,
jina-embeddings-v5-omni-nano, and it stays *frozen*.
Inside it there are two internal submodels,
a vision tower, and a text tower.
We never break them apart, and we never retrain them.//
Follow the image path first.
An image becomes sixteen pixel patches.
A patch is the vision tower's *internal* unit, not a crop.
Those patch tokens are *injected* into the text tower,
and two things come out.
Capital P, one row per patch,
where each row is shaped by attention over the *whole* image.
And small g, one vector for the whole image,
pooled from the last token of that same sequence.//
Now the vocabulary path.
This one runs *once*, offline.
All hundred twenty-eight thousand tokens
go through the *same* text tower,
and we cache the results as E, the label matrix.
At test time, only the *image* path runs.//
And both paths end in the *same* space.
So any patch, of any image,
can be scored against *any word the model knows*.`},

  { n:7, sec:40, title:"The pipeline",
    note:`Here is the complete tagger, on one slide.//
The top lane runs *once*, offline.
We encode the vocabulary into the label matrix.
We estimate a background prior.
And we build the word gate.
We will meet each of these in a moment.//
The bottom lane runs *per image*.
One frozen forward pass gives us the patches and the global vector.
We score them against the labels. That is family *A*.
We subtract the prior.
We gate, and we dedupe.
And the top k tags come out. Seventy-five milliseconds.//
The teal box below is the optional high-quality mode.
Fourteen crops, back through the *same* model.
That is family *B*, new passes on new pixels.//
And notice, every box is either the frozen model, or plain arithmetic.`},

  { n:8, sec:42, title:"Step 1: the label space",
    note:`Step one. Where do the labels come from.//
There is no curated tag list.
We take all *one hundred twenty-eight thousand* tokens
in the tokenizer,
and we encode each one as text, into the label matrix E.
Now a single matrix multiply
scores an image against the entire vocabulary.//
But there is a trap here, and it cost us a day.
If you dot the image against the raw *embedding table*,
you get garbage.
Tutor. Avatar. PyTuple.
The reason is that this model *unties*
its input and output embeddings.
The input table lives in a different space
than the pooled output.
You have to run each token *through the tower*, as a text string,
to put the labels in the same space as the image.//
So the intuition, use the vocabulary directly, was right.
But only through the aligned output space.`},

  { n:9, sec:40, title:"Step 2: patch beats global",
    note:`Step two. Where do you *look* in the image.//
On the left, the global vector g, scored against each label.
One vector, dominated by the most salient object.
Mean average precision, *point two six*.//
On the right is what we do instead.
Every patch row is scored against *every* label,
and each label keeps its max over the patches.
If you know ColBERT, this *is* late interaction.
The patches play the role of the token vectors.
MaxSim, per label.
A small object fires on its *own* patch.
And that jumps the mAP to *point six three*.
Plus zero-point-three-seven, in one line of algebra.//
Here is the test-time compute reading.
This is pure family *A*.
The patch features already exist in the forward pass.
It is one extra max over the rows. Essentially free.`},

  { n:10, sec:32, title:"Step 3: subtract the prior",
    note:`Step three. A quick de-biasing.//
Raw cosine has a base-rate problem.
Some generic words, like bed, or cat,
score high on *almost any* image,
just because they sit close to the image modality.//
So we estimate a per-label prior, mu,
from a handful of neutral background images, once,
and we subtract it.
The strip under the chart shows the actual pools we used.
In the study, ordinary photos.
In the app port, *procedural* neutrals,
gradients, flat fields, noise.
No real data needed at all.
A word that scores high on *everything*
gets centered back to zero.
Only the image-specific spikes survive.//
No calibration set. No labels. One offline pass.
It is the lightest correction possible, and it is enough.`},

  { n:11, sec:32, title:"Step 4: word gate and NMS",
    note:`Step four. Cleaning up the output.//
The tokenizer *already* knows what a word is.
Byte-level tokenizers encode a leading space
as a special glyph.
That G-with-a-dot on the slide is exactly that glyph.
It is a tokenizer artifact, *not* a rendering error.
A token that starts with it starts a *new word*.
So space-cat is a whole word,
but GetComponent is a fragment.
That one built-in signal
filters a hundred twenty-eight thousand tokens
down to about *twenty-five thousand* clean words.
No external dictionary.//
Then we run embedding NMS,
non-maximum suppression, in embedding space.
We walk the labels by score,
and we keep a word only if its cosine
to everything already kept is below zero point six.
The funnel on the right is the real ranking for the cat image.
Cat, kitten, chatte, cats, all struck out, suppressed by kitty.
Again, no lookup table. Just the geometry.`},

  { n:12, sec:42, title:"Step 5: CWR multi-crop",
    note:`Step five. And this is the important one.
This is the *only* lever that genuinely raises accuracy.//
We re-encode the image as a grid of *fourteen crops*.
And notice the distinction.
A patch is the tower's internal unit.
A crop is a new *input image*,
which gets re-patchified itself.
Watch the overlay sweep the image.
Three by three, then two by two, then the center.
Each crop is a full forward pass
through the *same* frozen model.
And we take the per-label max across the crops.
A small object becomes *large*
in whichever crop contains it,
so its signal jumps from weak to strong.//
Look at the photo.
A single pass says wolf, roar, muzzle.
With multi-crop, it recovers the *bear*.//
And one detail matters enormously.
It is per-label *max*, not averaging.
Blind crop averaging actually made things *worse*.
For a small object, only one crop holds the evidence.
The outlier crop is not noise. It *is* the signal.`},

  { n:13, sec:40, title:"One equation",
    note:`Let me now assemble all five steps,
because the entire tagger is *one scoring function*.//
First term. The patch evidence.
Max over the patch rows, minus its prior.
Family A. Free. Plus point three seven of mAP.//
Second term. The global context.
The pooled vector, minus its own prior.
Also family A. Also free.//
Third term. The multi-crop max.
Fourteen fresh forward passes.
Family B. Fourteen times the cost, plus point zero seven five.//
And notice the third term is *recursive*.
S c l is the same patch-plus-global score,
applied to each crop as a fresh image.//
Then we gate to real words,
dedupe by cosine, and take the top k.
And that is it.
No head. No logits. No learned threshold.
*Every symbol* in that equation
is either the frozen model, or a max.`},

  { n:14, sec:40, title:"The equation, over the vocabulary",
    note:`And here is that equation,
watched over the *whole* vocabulary.
This is real data, for the cat image. Not a sketch.//
Stage one. The raw fused score,
all hundred twenty-eight thousand tokens.
A smooth bell.
Every token is *somewhat* close to every image.
There is no signal you can threshold here.//
Stage two. Subtract each token's own prior.
The mass snaps to zero.
And what remains on the *right tail* is the evidence.//
Stage three. The word-start gate.
A hundred twenty-eight thousand candidates
become twenty-five thousand.
The shape survives. The fragments do not.//
Stage four. Zoom into that right tail.
The top eight tokens are
kitty, cat, kitten, chatte, kitt, cats, kittens.
*One concept*, in seven forms.
And that is exactly what embedding NMS is for.
It keeps one, and the final tags fall out.//
So tagging, in one sentence, is *distribution sharpening*.`},

  { n:15, sec:30, title:"Results",
    note:`Here is the full progression,
on a hundred and fifty real COCO images,
with true multi-label ground truth.//
Global pooling, the weak baseline, mAP point two six.
Patch scoring, point six three.
And with multi-crop, *point seven one*,
with precision at one over *eighty percent*.//
That is the headline number from slide two,
now with the full ablation behind it.`},

  { n:16, sec:40, title:"Does bootstrapping scale?",
    note:`Now the experiment behind that conclusion.//
Every published bootstrap lever,
re-implemented, and measured on COCO.//
Read the chart as a dumbbell.
The open circle is the pipeline the lever starts from.
The filled circle is where it ends up.//
The two blue bars on top are our own wins.
Five-crop re-encoding, plus point zero five eight.
Fourteen-crop, plus point zero seven five.
Their endpoints, point six nine and point seven one,
are the baselines the other levers start from.//
Take OTTER, optimal transport.
It re-balances the scores
toward a target class distribution.
Pure re-arrangement, nothing new.
It sits on the five-crop pipeline,
so it starts at point six nine three.
And it moves *nothing*. Plus point zero zero six. Noise.//
Someone always asks, why not run it on fourteen-crop.
Because OTTER only corrects base-rate calibration,
and our prior subtraction already did that.
The crop count underneath does not change the verdict.//
Now look at the pink bars.
Whitening, graph propagation, Dirichlet.
Every one of them collapses, from wherever it starts.
Only feeding in new pixels moves us to the right.`},

  { n:17, sec:40, title:"The meta-conclusion",
    note:`So here is the meta-conclusion,
and it is the real payoff.//
Every method that *re-processes* the existing features
is a no-op, or a collapse.
Why?
Because those methods were designed for
weakly calibrated, *single-label*, two-tower CLIP.
This encoder's space is *already* aligned,
already calibrated, and already multi-label.
There is nothing left to recover by re-arranging it.//
The only thing that moves the ceiling
is *supplying the model with new pixels*.
Family C is the one that does not scale.
Real test-time compute means
giving the model more to *look at*,
not re-arranging what it already saw.`},

  { n:18, sec:42, title:"The frontier",
    note:`And here is everything, on one chart.
Accuracy, against *measured* latency per image.
Log scale.//
The frontier runs through four points.
Global only, fifty-two milliseconds, point two six.
Patch fusion, seventy-five milliseconds, point six three.
Five-crop re-encoding, four hundred milliseconds, point six nine.
Fourteen-crop, one second, point seven one.
You read more of the pass,
and then you re-encode new views.//
Now the pink points.
Re-processing costs under a tenth of a millisecond, measured.
So each one sits at the latency
of the pipeline it modifies,
at or below the frontier.//
Two honest footnotes.
Softmax over classes lands a thousandth above patch fusion.
Noise level. It is on the frontier anyway.
And OTTER lands six thousandths above five-crop on mAP,
but its precision at three *collapses*,
from point four five to point three.
That is why it is not adopted.
Free re-arrangement buys you noise.
Re-encoding buys you seven and a half points.`},

  { n:19, sec:30, title:"The next question",
    note:`One more question,
and it is a test-time compute question.//
Every tag so far is a *single word*.
Kitty. Cosy. Plush.//
But what if I want a noun *phrase*?
Grey couch kitty, not just kitty.//
Can I spend a little more compute at inference,
and get grounded modifiers,
with no part-of-speech tagger,
no grammar, and no new model?
Just the frozen encoder.//
Let me show you how.`},

  { n:20, sec:40, title:"Beam mechanics",
    note:`Here is the search space,
drawn as a tree, with real numbers.//
On the left is the phrase template.
Two empty slots, then the noun, kitty, fixed.
Watch the slots fill as the search runs.//
Slot one. Expand the noun into candidate words.
Couch, grey, sleeps, sofa. Keep the best four.
Fleece and blanket are pruned.//
Slot two, and this is the real beam search.
We expand *every* one of the four survivors.
The encoder scores each full phrase against the region.
And the best four across *all* of those expansions survive.//
Notice where they land.
Three of the four come from the couch branch.
One comes from grey.
Sleeps and sofa fall below the beam.
There is no backtracking.
We just read the winner off the final beam.//
Grey couch kitty, plus point zero nine three.
It even beats couch grey kitty.
Same words, better order.
Word order, resolved by an embedding model, with no grammar.`},

  { n:21, sec:28, title:"Qualitative results",
    note:`And it holds up outside the benchmark.
Each row is one photo, four modes, top five each.//
Default, the single pass.
Crops, the fourteen-crop re-encoding.
And beam-searched n-grams, at two, and at three.//
The Porsche is the clearest.
The single pass returns fragments. Driv. Sidew.
Re-encoding turns them into words.
Carro, windshield, steering.
And the n-grams ground the modifiers.
Windshield driv. Blackjack windshield driv.//
One miss survives, synagogue, on the corridor.
That is the honest cost
of a zero-annotation open vocabulary.
All of it verbatim. Nothing cherry picked.`},

  { n:22, sec:32, title:"Relation to prior work",
    note:`To place this against the literature, in one table.//
The RAM line trains a tagging model on a curated tag list.
We do zero training,
and our labels *are* the tokenizer vocabulary.
TagCLIP uses a two-tower CLIP,
and the second-to-last layer.
We use one omni model,
where the *last* layer is the output space.
PIAA whitens to close the modality gap.
But our image and text are *already* one space,
so whitening collapses it.//
Research question one. Yes.
A frozen embedding model becomes a tagger.
Research question two.
Only compute that adds information scales it.
The contribution is the *combination*,
plus the negative results.
We empirically ruled out
the test-time machinery everyone else is adding.//
And this combination is cheap enough to run on a laptop.
Which brings me to deployment.`},

  { n:23, sec:44, title:"Deployment in Omni",
    note:`And this did not stay a Python study.
It is deployed, in Omni,
a native on-device search app I built,
in Swift, on the same frozen model.
Every image on my Mac is tagged this way, today.//
The production story is where the design pays off.
The patch rows *already exist*,
for the file's embedding.
So tagging rides the same forward pass.
One extra matrix multiply,
against a memory-mapped label matrix.
About zero point six milliseconds per image.
Four percent overhead.
Effectively *free* at index time.//
The tags land in the search snippet.
So your photos and videos
become findable by *keyword*, not just by vector.
And the background prior calibrates itself,
on device, from the first sixty-four images it sees.`},

  { n:24, sec:46, title:"Every media shape",
    note:`And here is my favorite part of the port.
One label matrix, one scoring rule,
and it covers *every media shape* in the app.//
A plain image is tagged at index time,
inside the embedding pass.//
For high quality,
a background re-tag pass adds crops.
Two by two with fifteen percent overlap, plus the center.
In production we ship *five* crops instead of fourteen,
because fourteen only adds one point of mAP,
for triple the cost.
Precision at one goes from point seven seven, to *point eight five*.//
Video is the elegant one.
We sample up to thirty-two frames per four-minute segment,
and they go through the tower as *one sequence*.
So the patch max pools over space *and* time.
A bear in one frame of one segment still fires.//
And scanned PDFs render each page to an image,
and take exactly the same path.
Invoice, table, signature, per page.//
So the media shape only changes *what counts as a patch*.
Crops for detail. Frames for time. Pages for documents.`},

  { n:25, sec:36, title:"The bigger picture",
    note:`Let me place this in the bigger picture.
Test-time compute for embedding models.//
A frozen embedding model
exposes only part of what it can do.
Spend compute at inference,
extra passes, algebra over its outputs,
and you reach the rest.
No new parameters.//
In my AIE San Francisco talk,
I spent that compute for more *relevance*.
Better retrieval, on the task the encoder *was* trained for.//
In this talk, I spent it for a new *capability*.
Image tagging.
A task the encoder was *never* trained for.//
It is the same lever, escalating,
from quality, to capability.
And it only pays
when the compute feeds the model *new information*.`},

  { n:26, sec:26, title:"Close",
    note:`So this is the sentence
I want to leave you with.
Scaling test-time compute of an embedding model
unlocks tasks *beyond retrieval*.
But only the compute that carries new information scales.//
The code, the benchmark,
and every negative result are on GitHub.
And it all runs on a Mac.
Thank you.
I would love your questions.`},

];
